routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');

    Route::resource('posts', 'PostsController');

    Route::resource('tags', 'TagsController');

    Route::get('trashed_posts', 'PostsController@trashed');

    Route::put('restore_post/{post}', 'PostsController@restore')->name('restore_post');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users', 'UsersController@index')->name('users');
    Route::post('users/{user}/make_admin', 'UsersController@makeAdmin')->name('users.make_admin');
    Route::get('users/edit_profile', 'UsersController@editProfile')->name('user.edit_profile');
    Route::put('users/update_profile', 'UsersController@updateProfile')->name('users.update_profile');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TagRequest;
use App\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::oldest()->paginate(5);

        return view('tags.index',compact('tags'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        Tag::create($request->all());
        return redirect()->route('tags.index')
            ->with('success','Tag created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, Tag $tag)
    {
        $tag->update($request->all());
        return redirect()->route('tags.index')
            ->with('success','Tag updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if ($tag->posts->count() > 0) {
            return redirect()->route('tags.index')
                ->with('error','Tag to be deleted must be empty');
        }

        $tag->delete();

        return redirect()->route('tags.index')
            ->with('success','Tag deleted successfully');
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')
@section('content')


    <div class="row">
        <div class="col-12 text-center">
            <div class="card card-default">
                <div class="card-header">
                    <h4>new tag</h4>
                </div>
                <div class="card-body">
                    <form action="{{route('tags.store')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <input class="form-control" type="text" name="name" placeholder="tag name">
                        </div>
                        <button class="btn btn-success" type="submit">add tag</button>
                    </form>
                </div>
            </div>
        </div>

@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')
@section('content')


    <div class="row">
        <div class="col-12 text-center">
            <div class="card card-default">
                <div class="card-header">
                    <h4>edit tag</h4>
                </div>
                <div class="card-body">
                    <form action="{{route('tags.update', $tag->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <input class="form-control" type="text" name="name" placeholder="tag name"
                                   value="{{old('name') ?? $tag->name}}">
                        </div>
                        <button class="btn btn-primary" type="submit">edit tag</button>
                    </form>
                </div>
            </div>
        </div>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <a href="{{route('tags.create')}}">
                        <button class="btn btn-success float-right">new tag</button>
                    </a>
                    <h4>Tags:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        @forelse ($tags as $tag)
                            <li class="list-group-item">

                                <span>{{$tag->id}}. {{ $tag->name }}</span>
                                <span>Post count: {{$tag->posts()->count()}}</span>

                                <span class="dropdown">
                                    <button class="btn btn-info btn-sm float-right dropdown-toggle" type="button"
                                            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="false">
                                        options
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <form action="{{ route('tags.destroy',$tag->id) }}" method="POST">
                                            <a class="dropdown-item"
                                               href="{{ route('tags.edit',$tag->id) }}">Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="dropdown-item" onclick="return confirm('Are you sure?')">Delete</button>
                                        </form>
                                    </div>
                                </span>

                            </li>
                        @empty
                            <p>No tags</p>
                        @endforelse
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row pagination justify-content-center sticky-bottom my-5">
        <div class="">{{$tags}}</div>
    </div>
@endsection