routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');

    Route::resource('posts', 'PostsController');

    Route::resource('tags', 'TagsController');

    Route::get('trashed_posts', 'PostsController@trashed');

    Route::put('restore_post/{post}', 'PostsController@restore')->name('restore_post');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users', 'UsersController@index')->name('users');
    Route::post('users/{user}/make_admin', 'UsersController@makeAdmin')->name('users.make_admin');
    Route::get('users/edit_profile', 'UsersController@editProfile')->name('user.edit_profile');
    Route::put('users/update_profile', 'UsersController@updateProfile')->name('users.update_profile');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = ['title', 'description', 'image', 'content', 'published_at', 'category_id'];


    /**
     *  Delete post image from Storage
     *
     * @return void
     */
    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    /**
     * Relacje
     * Nazwa modelu z małej litery
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function hasTag($tag_id)
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray(), true);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\PostsRequest;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PostsController extends Controller
{
    /**
     * PostsController constructor.
     */
    public function __construct()
    {
        $this->middleware('verifyCategoryCount')->only(['create', 'store']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::oldest()->paginate(5);

        return view('posts.index',compact('posts'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')
            ->with('tags', Tag::all())
            ->with('categories', Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostsRequest $request)
    {
        $post_content = $request->all('post-trixFields');
        $image = (isset($request->image) ? $request->image->store('posts') : null);
        $post = Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $post_content['post-trixFields']['post_content'],
            'published_at' => strtotime($request->published_at),
            'image' => $image,
            'category_id' => $request->category,
        ]);

        if ($request->tags) {
            $post->tags()->attach($request->tags);
        }

        return redirect()->route('posts.index')
            ->with('success','Post created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        if ($request->hasFile('image')) {
            $image = $request->image->store('posts');
            $post->deleteImage();
            $data['image'] = $image;
        } else {
            $image = $post->image;
        }

        $post->update([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $request->post_content,
            'published_at' => strtotime($request->published_at),
            'image' => $image,
            'category_id' => $request->category,
        ]);

        if ($request->tags) {
            $post->tags()->sync($request->tags);
        }

        return redirect()
            ->route('posts.index')
            ->with('success', 'Post updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();

        if ($post->trashed()) {
            $post->deleteImage();
            $post->forceDelete();
            session()->flash('success','Post deleted successfully.');
        } else {
            $post->delete();
            session()->flash('success','Post trashed successfully.');
        }

        return redirect()->route('posts.index');
    }

    /**
     * Display list of all trashed posts
     */
    public function trashed()
    {
        $posts = Post::onlyTrashed()->paginate(5);
        return view('posts.index',compact('posts'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();
        $post->restore();
        return redirect()
            ->route('posts.index')
            ->with('success', 'Post restored successfully!');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h4>new post</h4>
                </div>
                <div class="card-body">
                    <form action="{{route('posts.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <input class="form-control" type="text" name="title" placeholder="post name">
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" name="description" placeholder="post description">
                        </div>
                        <div class="form-group">
                            @trix(\App\Post::class, 'post_content')
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" value="{{date('d-m-Y G:i',time())}}"
                                   name="published_at" id="published_at" placeholder="post publish_at">
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="category">category</label>
                            </div>
                            <select class="custom-select" id="category" name="category">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">
                                        {{$category->name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="tags">tags (select with pressing shift)</label>
                            </div>
                            <select class="custom-select" multiple id="tags" name="tags[]">
                                @foreach($tags as $tag)
                                    <option value="{{$tag->id}}">
                                        {{$tag->name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <input class="form-control" type="file" name="image" placeholder="post image">
                        </div>
                        <div class="form-group text-center">
                            <button class="btn btn-success" type="submit">add post</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h4>edit post</h4>

                </div>
                <div class="card-body">
                    <form action="{{route('posts.update', $post->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <input class="form-control" type="text" name="title" placeholder="post name"
                                   value="{{old('title') ?? $post->title}}">
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" name="description" placeholder="post description"
                                   value="{{old('description') ?? $post->description}}">
                        </div>
                        <div class="form-group">
                            <input id="post_content" value="" type="hidden" name="post_content">
                            <trix-editor input="post_content">{!! $post->content !!}</trix-editor>
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="inputGroupSelect01">category</label>
                            </div>
                            <select class="custom-select" id="inputGroupSelect01" name="category">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}"
                                            @if($category->id == $post->category_id)
                                            selected
                                        @endif
                                    >
                                        {{$category->name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="tags">tags (select with pressing shift)</label>
                            </div>
                            <select class="custom-select" multiple id="tags" name="tags[]">
                                @foreach($tags as $tag)
                                    <option value="{{$tag->id}}"
                                        @if($post->hasTag($tag->id))
                                            selected
                                        @endif
                                    >
                                        {{$tag->name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <input class="form-control" type="text"
                                   value="{{date('d-m-Y G:i', old('published_at') ?? $post->published_at)}}"
                                   name="published_at" id="published_at" placeholder="post publish_at">
                        </div>
                        @if($post->image)
                            <div class="mt-5">
                                <img src="{{asset('storage/'. $post->image)}}" class="img-fluid"
                                     alt="{{$post->description}}">
                            </div>
                        @endif
                        <div class="form-group">
                            <input class="form-control" type="file" name="image" placeholder="post image"
                                   value="{{old('image') ?? $post->image}}">
                        </div>
                        <div class="form-group text-center">
                            <button class="btn btn-success" type="submit">edit post</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <a href="{{route('posts.create')}}">
                        <button class="btn btn-success float-right">add post</button>
                    </a>
                    <h4>Posts:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        @forelse ($posts as $post)
                            <li class="list-group-item">

                                <span>{{$post->id}}. {{ $post->title }}</span>
                                <span class="dropdown">
                                    <button class="btn btn-info btn-sm float-right dropdown-toggle" type="button"
                                            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="false">
                                        options
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                                            @if(!$post->trashed())
                                            <a class="dropdown-item"
                                               href="{{ route('posts.edit',$post->id) }}">Edit</a>
                                        @else
                                            <form action="{{route('restore_post',$post->id)}}" method="post">
                                                    @csrf
                                                @method('PUT')
                                                    <button class="dropdown-item"
                                                            type="submit">Restore</button>
                                                </form>
                                        @endif
                                        <form action="{{ route('posts.destroy',$post->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="dropdown-item"
                                                    onclick="return confirm('Are you sure?')">
                                                {{$post->trashed() ? 'Delete' : 'Trash'}}
                                            </button>
                                        </form>

                                    </div>
                                </span>

                                @if($post->image)
                                    <div class="mt-5">
                                        <img src="{{asset('storage/'. $post->image)}}" class="img-fluid"
                                             alt="{{$post->description}}">
                                    </div>
                                @endif

                            </li>
                        @empty
                            <p>No posts</p>
                        @endforelse
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row pagination justify-content-center sticky-bottom my-5">
        <div class="">{{$posts}}</div>
    </div>
@endsection